sudo: false
language: node_js
node_js:
  - "6"
cache: bundler
before_install:
  - rvm install 2.0.0
  # http://blog.travis-ci.com/2014-10-30-november--build-environment-updates/
  - curl -L -o phantomjs.tar.bz2 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
  - mkdir ./phantomjs
  - tar xjf phantomjs.tar.bz2 -C ./phantomjs --strip-components=1
install:
  - npm install
script:
  - npm run build
  - cd test/dummy
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-../../vendor/bundle}
  - bundle exec guard-jasmine -b ../../phantomjs/bin/phantomjs --server-timeout=60
