sudo: false
language: ruby
cache: bundler
rvm: "1.9.3"
before_install:
  # http://blog.travis-ci.com/2014-10-30-november--build-environment-updates/
  - curl -L -O https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
  - tar xjf phantomjs-1.9.7-linux-x86_64.tar.bz2
  - export PATH=$PATH:phantomjs-1.9.7-linux-x86_64/bin/
script:
  - cd test/dummy
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install
  - bundle exec guard-jasmine --server-timeout=60
